%YAML:1.0

#common parameters
imu_topic: "/mynteye/imu/data_raw"
image_topic: "/mynteye/left/image_color"
output_path: "/home/lenovo/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: -0.2870635986328125
   k2: 0.06902313232421875
   p1: 0.000362396240234375
   p2: 0.000701904296875
projection_parameters:
   #fx: 349.199951171875
   #fy: 349.199951171875
   #cx: 322.2005615234375
   #cy: 246.161865234375
   fx: 349.199951171875
   fy: 349.199951171875
   cx: 322.2005615234375
   cy: 246.161865234375
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999894, -0.0105982,  0.0100214,
           -0.0106528, -0.999929, 0.0054139, 
           0.00996336, -0.00552008, -0.999935]  
   
#data: [0.999955, -0.00474663,  0.00821505,
           #-0.00475461, -0.999988, 0.000952886, 
           #0.00821043, -0.000991903, -0.999966]
        
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   #data: [-0.04777362, -0.00223731, -0.00160071]
   data: [-0.0487123, 0.00717749, -0.0292568]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.1657228523252730e-02          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 2.1923690143745844e-03         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 3.8153871149178200e-03         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.4221215955051228e-04      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.79754     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/lenovo/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.013                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
